mysql:
  ali:
    host: "rm-2zelx1n8s1qx94828.mysql.rds.aliyuncs.com"
#    host: "rm-2zelx1n8s1qx948289o.mysql.rds.aliyuncs.com" # 公网
    port: "3306"
    user: "code"
    password: "SZc19970517"
    db_name: "plant"
    charset: "utf8mb4"
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_life_time: 3600
  ali2:
    host: "rm-2zelx1n8s1qx948289o.mysql.rds.aliyuncs.com"
    port: "3306"
    user: "code"
    password: "SZc19970517"
    db_name: "szc"
    charset: "utf8mb4"
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_life_time: 3600
redis:
  ali:
#    host: "r-2zesnyi6lh3n4udnbc.redis.rds.aliyuncs.com" # 专网
    host: "r-2zesnyi6lh3n4udnbcpd.redis.rds.aliyuncs.com" # 公网
    port: "6379"
    user: "code"
    password: "m(5hladieGeWK@cL+o$YA#wL8((p9h$3"
    db_name: 0
    pool_size: 20